export const FETCH_GET_QUESTIONS_LIST_REQUEST = "FETCH_GET_QUESTIONS_LIST_REQUEST";
export const FETCH_GET_QUESTIONS_LIST_SUCCESS = "FETCH_GET_QUESTIONS_LIST_SUCCESS";
export const FETCH_GET_QUESTIONS_LIST_FAILURE = "FETCH_GET_QUESTIONS_LIST_FAILURE";
